import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    'introduction',
    'get-started',
    {
      type: 'category',
      label: 'Installation',
      items: [
        'installation/index',
        'installation/docker',
        'installation/kubernetes',
        'installation/distributed',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/index',
        'concepts/streams',
        'concepts/query',
        'concepts/users-roles',
      ],
    },
    {
      type: 'category',
      label: 'Log Ingestion',
      items: [
        'log-ingestion/index',
        'log-ingestion/fluentbit',
        'log-ingestion/vector',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/index',
      ],
    },
  ],
};

export default sidebars;
