openapi: 3.0.0
info:
  title: Parseable API
  version: 1.0.0
  description: |-
    Core APIs for Parseable - a simplified version of the API schema with only essential endpoints.
servers:
  - url: '{protocol}://{host}:{port}'
    variables:
      protocol:
        default: http
        enum:
          - http
          - https
      host:
        default: localhost
      port:
        default: '8000'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
paths:
  /api/v1/logstream/{stream_name}:
    put:
      tags:
        - Dataset Management
      summary: Create a log dataset
      operationId: createLogStream
      description: |
        This endpoint is used to create a new log dataset within Parseable.  
        A **log dataset** is a group of similar logs. For example, you can create a log dataset for a specific application's logs, another log dataset for your database logs, and so on. You can create as many log streams as needed to organize and manage logs efficiently.  
      security:
        - basicAuth: []
      parameters:
        - name: stream_name
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Dataset Management
      summary: Delete a log dataset
      operationId: deleteLogStream
      description: |
        This endpoint is used to delete an existing log dataset.
        When a log dataset is deleted, all associated data is permanently removed.
      security:
        - basicAuth: []
      parameters:
        - name: stream_name
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Dataset Management
      summary: Send logs to a dataset
      operationId: sendLogsToStream
      description: |
        **Log Ingestion API via Stream Endpoint**  
        In this approach, you need to create a dataset first using the **Create Stream API**.  
        Once the dataset is created, you can send logs to the dataset ingestion API endpoint:  
        **http://INGESTION_ENDPOINT/api/v1/logstream/{stream_name}**  
        This API does not require any headers for specifying the dataset name.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                - id: 434a5f5e-2f5f-11ed-a261-asdasdafgdfd
                  datetime: 24/Jun/2022:14:12:15 +0000
                  host: 153.10.110.81
                  user-identifier: >-
                    Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0)
                    Gecko/20100101 Firefox/64.0
                  method: PUT
                  status: 500
                  referrer: http://www.google.com/
      security:
        - basicAuth: []
      parameters:
        - name: stream_name
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/query:
    post:
      tags:
        - Query API
      summary: Query a log dataset
      operationId: queryLogStream
      description: |
        **Parseable Log Query API**  
        This endpoint allows you to query logs using PostgreSQL syntax.  
        
        The query API accepts the following parameters:
        - **query**: The SQL query to execute (required)
        - **startTime**: The start time for the query range (optional)
        - **endTime**: The end time for the query range (optional)
        - **streamName**: The name of the log dataset to query (required)
        
        Example request body:
        ```json
        {
          "query": "SELECT * FROM log WHERE log ILIKE '%error%';",
          "startTime": "2023-01-01 00:00:00.000000",
          "endTime": "2023-01-01 23:59:59.999999",
          "streamName": "example-dataset"
        }
        ```
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - streamName
              properties:
                query:
                  type: string
                startTime:
                  type: string
                endTime:
                  type: string
                streamName:
                  type: string
      security:
        - basicAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/ingest:
    post:
      tags:
        - Log Ingestion
      summary: Ingest logs with headers
      operationId: ingestLogsWithHeaders
      description: |
        **Log Ingestion API via Custom Headers**  
        This approach allows you to send logs to Parseable using custom headers to specify the target dataset.  
        
        Required headers:
        - **X-P-Stream**: The name of the dataset to ingest logs into
        
        The API accepts logs in JSON format. You can send single log entries or arrays of log entries.
        
        Example:
        ```json
        {
          "level": "info",
          "message": "User logged in",
          "timestamp": "2023-01-01T12:00:00Z",
          "user_id": "user123"
        }
        ```
        
        Or as an array:
        ```json
        [
          {
            "level": "info",
            "message": "User logged in",
            "timestamp": "2023-01-01T12:00:00Z",
            "user_id": "user123"
          },
          {
            "level": "error",
            "message": "Failed to process request",
            "timestamp": "2023-01-01T12:01:00Z",
            "error_code": "ERR-1001"
          }
        ]
        ```
      requestBody:
        content:
          application/json:
            schema:
              type: object
      security:
        - basicAuth: []
      parameters:
        - name: X-P-Stream
          in: header
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
